### ISSUE TITLE
Missing getter for ConnectLoginButton click listener in 1.9.3

### ISSUE THREAD

**Issue by simonnorberg** [telenordigital/connect-android-sdk#148]
Hi, we need access to the ConnectLoginButton click listener in our app. Looks like the getter was removed in 1.9.3. 

https://github.com/telenordigital/connect-android-sdk/commit/d0a9e256485dfddd19ffce4c933ed7f64da147f3#diff-3571a6f26446acc775adf084717264bdL62

Can you restore the getter?

**Comment by jorunfa** [comment]
Added the task to the backlog. Will get to it as soon as I can, but might be a little while.
