### ISSUE TITLE
Unable to destroy activity Crash

### ISSUE THREAD

**Issue by rashel007** [telenordigital/connect-android-sdk#157]
Getting Crash in 1.9.4 version 

`Fatal Exception: java.lang.RuntimeException
Unable to destroy activity {mm.cws.telenor.app/com.telenor.connect.ui.ConnectActivity}: java.util.ConcurrentModificationException`

**Comment by rashel007** [comment]
This is what i am getting in Fabric report

`

java.util.HashMap$HashIterator.nextEntry (HashMap.java:787)
--
  | java.util.HashMap$KeyIterator.next (HashMap.java:814)
  | com.telenor.connect.ui.ConnectActivity.onDestroy (Unknown Source)
  | android.app.Activity.performDestroy (Activity.java:6458)
  | android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1149)
  | android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4011)
  | android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:4042)
  | android.app.ActivityThread.access$1500 (ActivityThread.java:180)
  | android.app.ActivityThread$H.handleMessage (ActivityThread.java:1529)
  | android.os.Handler.dispatchMessage (Handler.java:111)
  | android.os.Looper.loop (Looper.java:207)
  | android.app.ActivityThread.main (ActivityThread.java:5710)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:900)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:761)

`

**Comment by simonnorberg** [comment]
Looks like a `ConcurrentModificationException` can happen here in onDestroy.
https://github.com/telenordigital/connect-android-sdk/blob/master/connect/src/com/telenor/connect/ui/ConnectActivity.java#L114

https://stackoverflow.com/questions/223918/iterating-through-a-collection-avoiding-concurrentmodificationexception-when-re
