### ISSUE TITLE
Connect ID Auth Token Expired 

### ISSUE THREAD

**Issue by AndDev-Qumber** [telenordigital/connect-android-sdk#169]
Getting the error token already used or expired in process of validation of token.

**Comment by SerhiiBovtriuk** [comment]
Hello, @AndDev-Qumber, can you please provide more details about what you do and what is happening wrong?

**Comment by SerhiiBovtriuk** [comment]
Been inactive for a month now. Moving issue to "wontfix" state. 

In case if problem reappear, please, reopen the thread.
