### ISSUE TITLE
Enable mobile data dialog always shows, even if on mobile data

### ISSUE THREAD

**Issue by hegge** [telenordigital/connect-android-sdk#206]
If `ENABLE_TURN_ON_MOBILE_DATA_DIALOG` is `true`, the dialog always shows, even if mobile data already is connected.

This is caused by `cellularNetwork` being set to `null` in `HeLogic.isCellularDataNetworkConnected()`.

If `automaticallyInitializeInstantVerification` is set to `true` when doing `ConnectSdk.sdkInitialize()`, the dialog responds to mobile data connection as expected, as `initializeCellularNetwork()` is called.

Tested on Sony Xperia XZ1 Compact, Android 9

**Comment by SerhiiBovtriuk** [comment]
Hello, thanks for the report.

The case doesn't look critical at this point, but I will check it out and it might receive a fix in incoming versions of SDK.
