### ISSUE TITLE
Disable login with email

### ISSUE THREAD

**Issue by infinityzero** [telenordigital/connect-android-sdk#24]
We can sign-in using phone number or email and that is great feature. But I need only sign-in using phone number. So, is there any way to disable "Switch to email" display?

**Comment by jorunfa** [comment]
It is not currently possible but we will make it so in the future. It will work so that you can provide a preferred username type, and then lock it down to that.

I will try to keep this issue up to date with the progress.

**Comment by jorunfa** [comment]
Do you want this feature because you want to make sure the user registers his/her phone number?

If so you can use the [claims parameter](http://docs.telenordigital.com/apis/connect/id/authentication.html) to make sure they have to enter this.

**Comment by jorunfa** [comment]
Is this still an issue? I heard it might have been fixed by some other measure.

**Comment by infinityzero** [comment]
Sorry for late reply. There are no more issue.
