### ISSUE TITLE
Crash when following Basic usage guide

### ISSUE THREAD

**Issue by rasmusohrstig** [telenordigital/connect-android-sdk#87]
I found a small problem in the Basic usage guide.

The Basic usage guide advices you to call ConnectSdk.sdkInitialize(getApplicationContext()) after calling Activity.setContentView() in Activity.onCreate(). If the layout passed to setContentView contains a ConnectLoginButton the app will crash with a ConnectNotInitializedException. 

This is probably fine, since Connect is not initialized.

You can solve the problem by calling ConnectSdk.sdkInitialize(getApplicationContext()) before setContentView.

Another approach is to override Application.onCreate() and call ConnectSdk.sdkInitialize(this) there. The benefit of the latter approach is that ConnectSdk.sdkInitialize will always have been called before your activity is created regardless of which activity it is and how you ended up there.

**Comment by jorunfa** [comment]
I see your point. Will look into it when time allows.
