### ISSUE TITLE
Refresh/access tokens are logged in production

### ISSUE THREAD

**Issue by simonnorberg** [telenordigital/connect-android-sdk#98]
It seems the SDK is logging all requests made with Retrofit to Logcat. Including the response with refresh/access tokens visible. This is convenient while developing, but very bad in production from a security and performance perspective.

From what I can see logging is configured in RestHelper:
https://github.com/telenordigital/connect-android-sdk/blob/8e577a2a3e4a27f815c16e9664d1ef98759d845f/connect/src/com/telenor/connect/utils/RestHelper.java#L76

This should be set to `RestAdapter.LogLevel.NONE` in production builds. Maybe it can be configurable by the app using the SDK?

**Comment by jorunfa** [comment]
Good point, I'm in full agreement 👍. Will see when we find the time to correct this - the main SDK developers have been on vacation, and there is a small backlog.
